app:
  env: "development" # production/staging
  grpc_port: 50052
  shutdown_timeout: 30s

mysql:
  dsn: "root:root@tcp(127.0.0.1:3306)/shop?charset=utf8mb4&parseTime=True&loc=Local"


redis:
  host: "127.0.0.1"
  port: 16379
  password: "redispass"
  db: 0
  pool_size: 20

auth:
  jwt_secret: "wenshuai"
  access_token_expire: "15m"
  refresh_token_expire: "7d"
  issuer: "old_user-service"

nacos:
  host: '127.0.0.1'
  port: 8848
  namespace: 'd70834dc-214d-49f3-a960-d4fba6b6e576'
  user: 'nacos'
  password: 'nacos'
  dataid: 'config.json'
  group: 'dev'

consul:
  # 必需配置
  host: "127.0.0.1"             # Consul 服务器地址
  port: 8500                    # Consul HTTP API 端口
  # 可选配置
  scheme: "http"                # http 或 https
  token: ""                     # ACL token（如有ACL保护）
  datacenter: "dc1"             # 数据中心名称
  wait_time: "30s"              # 阻塞查询超时时间

server:
  name: user-service          # 服务名称（在 Consul 中的注册名）
  host: 127.0.0.1               # gRPC 服务监听地址
  port: 50052                # gRPC 服务监听端口
  tags: ["grpc", "user"]      # 可选：服务标签
  check_interval: "10s"       # Consul 健康检查间隔
  check_timeout: "5s"         # Consul 健康检查超时
  id: "1"
