app:
  env: "development" # production/staging
  grpc_port: 50051
  shutdown_timeout: 30s

redis:
  host: "127.0.0.1"
  port: 6379
  password:
  db: 0
  pool_size: 20


smtp:
  from: 996948441@qq.com
  from_alias: gstecp
  host: "smtp.qq.com:465"
  password: uaadriruhhr
  port: "465"

consul:
  # 必需配置
  host: "127.0.0.1"             # Consul 服务器地址
  port: 8500                    # Consul HTTP API 端口
  # 可选配置
  scheme: "http"                # http 或 https
  token: ""                     # ACL token（如有ACL保护）
  datacenter: "dc1"             # 数据中心名称
  wait_time: "30s"              # 阻塞查询超时时间

server:
  name: code-service          # 服务名称（在 Consul 中的注册名）
  host: 127.0.0.1               # gRPC 服务监听地址
  port: 50051                 # gRPC 服务监听端口
  tags: ["grpc", "code"]      # 可选：服务标签
  check_interval: "10s"       # Consul 健康检查间隔
  check_timeout: "5s"         # Consul 健康检查超时
  id: "1"   
