// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: inventory.proto

package inventoryclient

import (
	"context"

	"shop/inventory/inventory"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty              = inventory.Empty
	GoodsInventoryInfo = inventory.GoodsInventoryInfo
	SellInfo           = inventory.SellInfo

	Inventory interface {
		SetInv(ctx context.Context, in *GoodsInventoryInfo, opts ...grpc.CallOption) (*Empty, error)
		InvDetail(ctx context.Context, in *GoodsInventoryInfo, opts ...grpc.CallOption) (*GoodsInventoryInfo, error)
		Sell(ctx context.Context, in *SellInfo, opts ...grpc.CallOption) (*Empty, error)
		Reback(ctx context.Context, in *SellInfo, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultInventory struct {
		cli zrpc.Client
	}
)

func NewInventory(cli zrpc.Client) Inventory {
	return &defaultInventory{
		cli: cli,
	}
}

func (m *defaultInventory) SetInv(ctx context.Context, in *GoodsInventoryInfo, opts ...grpc.CallOption) (*Empty, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.SetInv(ctx, in, opts...)
}

func (m *defaultInventory) InvDetail(ctx context.Context, in *GoodsInventoryInfo, opts ...grpc.CallOption) (*GoodsInventoryInfo, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.InvDetail(ctx, in, opts...)
}

func (m *defaultInventory) Sell(ctx context.Context, in *SellInfo, opts ...grpc.CallOption) (*Empty, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.Sell(ctx, in, opts...)
}

func (m *defaultInventory) Reback(ctx context.Context, in *SellInfo, opts ...grpc.CallOption) (*Empty, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.Reback(ctx, in, opts...)
}
