// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package server

import (
	"context"

	"shop/order/internal/logic"
	"shop/order/internal/svc"
	"shop/order/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

// 购物车
func (s *OrderServer) CartItemList(ctx context.Context, in *order.UserInfo) (*order.CartItemListResponse, error) {
	l := logic.NewCartItemListLogic(ctx, s.svcCtx)
	return l.CartItemList(in)
}

func (s *OrderServer) CreateCarItem(ctx context.Context, in *order.CartItemRequest) (*order.ShopCartInfoResponse, error) {
	l := logic.NewCreateCarItemLogic(ctx, s.svcCtx)
	return l.CreateCarItem(in)
}

func (s *OrderServer) UpdateCartItem(ctx context.Context, in *order.CartItemRequest) (*order.Empty, error) {
	l := logic.NewUpdateCartItemLogic(ctx, s.svcCtx)
	return l.UpdateCartItem(in)
}

func (s *OrderServer) DeleteCartItem(ctx context.Context, in *order.CartItemRequest) (*order.Empty, error) {
	l := logic.NewDeleteCartItemLogic(ctx, s.svcCtx)
	return l.DeleteCartItem(in)
}

// 订单
func (s *OrderServer) CreateOrder(ctx context.Context, in *order.OrderRequest) (*order.OrderInfoResponse, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *OrderServer) OrderList(ctx context.Context, in *order.OrderFilterRequest) (*order.OrderListResponse, error) {
	l := logic.NewOrderListLogic(ctx, s.svcCtx)
	return l.OrderList(in)
}

func (s *OrderServer) OrderDetail(ctx context.Context, in *order.OrderRequest) (*order.OrderInfoDetailResponse, error) {
	l := logic.NewOrderDetailLogic(ctx, s.svcCtx)
	return l.OrderDetail(in)
}

func (s *OrderServer) UpdateOrderStatus(ctx context.Context, in *order.OrderStatus) (*order.Empty, error) {
	l := logic.NewUpdateOrderStatusLogic(ctx, s.svcCtx)
	return l.UpdateOrderStatus(in)
}
