// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: goods.proto

package server

import (
	"context"

	"shop/goods_gozero/goods"
	"shop/goods_gozero/internal/logic"
	"shop/goods_gozero/internal/svc"
)

type GoodsServer struct {
	svcCtx *svc.ServiceContext
	goods.UnimplementedGoodsServer
}

func NewGoodsServer(svcCtx *svc.ServiceContext) *GoodsServer {
	return &GoodsServer{
		svcCtx: svcCtx,
	}
}

// 商品接口
func (s *GoodsServer) GoodsList(ctx context.Context, in *goods.GoodsFilterRequest) (*goods.GoodsListResponse, error) {
	l := logic.NewGoodsListLogic(ctx, s.svcCtx)
	return l.GoodsList(in)
}

// 现在用户提交订单有多个商品，你得批量查询商品的信息吧
func (s *GoodsServer) BatchGetGoods(ctx context.Context, in *goods.BatchGoodsIdInfo) (*goods.GoodsListResponse, error) {
	l := logic.NewBatchGetGoodsLogic(ctx, s.svcCtx)
	return l.BatchGetGoods(in)
}

func (s *GoodsServer) CreateGoods(ctx context.Context, in *goods.CreateGoodsInfo) (*goods.GoodsInfoResponse, error) {
	l := logic.NewCreateGoodsLogic(ctx, s.svcCtx)
	return l.CreateGoods(in)
}

func (s *GoodsServer) DeleteGoods(ctx context.Context, in *goods.DeleteGoodsInfo) (*goods.Empty, error) {
	l := logic.NewDeleteGoodsLogic(ctx, s.svcCtx)
	return l.DeleteGoods(in)
}

func (s *GoodsServer) UpdateGoods(ctx context.Context, in *goods.CreateGoodsInfo) (*goods.Empty, error) {
	l := logic.NewUpdateGoodsLogic(ctx, s.svcCtx)
	return l.UpdateGoods(in)
}

func (s *GoodsServer) GetGoodsDetail(ctx context.Context, in *goods.GoodInfoRequest) (*goods.GoodsInfoResponse, error) {
	l := logic.NewGetGoodsDetailLogic(ctx, s.svcCtx)
	return l.GetGoodsDetail(in)
}

// 商品分类
func (s *GoodsServer) GetAllCategorysList(ctx context.Context, in *goods.Empty) (*goods.CategoryListResponse, error) {
	l := logic.NewGetAllCategorysListLogic(ctx, s.svcCtx)
	return l.GetAllCategorysList(in)
}

// 获取子分类
func (s *GoodsServer) GetSubCategory(ctx context.Context, in *goods.CategoryListRequest) (*goods.SubCategoryListResponse, error) {
	l := logic.NewGetSubCategoryLogic(ctx, s.svcCtx)
	return l.GetSubCategory(in)
}

func (s *GoodsServer) CreateCategory(ctx context.Context, in *goods.CategoryInfoRequest) (*goods.CategoryInfoResponse, error) {
	l := logic.NewCreateCategoryLogic(ctx, s.svcCtx)
	return l.CreateCategory(in)
}

func (s *GoodsServer) DeleteCategory(ctx context.Context, in *goods.DeleteCategoryRequest) (*goods.Empty, error) {
	l := logic.NewDeleteCategoryLogic(ctx, s.svcCtx)
	return l.DeleteCategory(in)
}

func (s *GoodsServer) UpdateCategory(ctx context.Context, in *goods.CategoryInfoRequest) (*goods.Empty, error) {
	l := logic.NewUpdateCategoryLogic(ctx, s.svcCtx)
	return l.UpdateCategory(in)
}

// 品牌
func (s *GoodsServer) BrandList(ctx context.Context, in *goods.BrandFilterRequest) (*goods.BrandListResponse, error) {
	l := logic.NewBrandListLogic(ctx, s.svcCtx)
	return l.BrandList(in)
}

func (s *GoodsServer) CreateBrand(ctx context.Context, in *goods.BrandRequest) (*goods.BrandInfoResponse, error) {
	l := logic.NewCreateBrandLogic(ctx, s.svcCtx)
	return l.CreateBrand(in)
}

func (s *GoodsServer) DeleteBrand(ctx context.Context, in *goods.BrandRequest) (*goods.Empty, error) {
	l := logic.NewDeleteBrandLogic(ctx, s.svcCtx)
	return l.DeleteBrand(in)
}

func (s *GoodsServer) UpdateBrand(ctx context.Context, in *goods.BrandRequest) (*goods.Empty, error) {
	l := logic.NewUpdateBrandLogic(ctx, s.svcCtx)
	return l.UpdateBrand(in)
}

// 轮播图
func (s *GoodsServer) BannerList(ctx context.Context, in *goods.Empty) (*goods.BannerListResponse, error) {
	l := logic.NewBannerListLogic(ctx, s.svcCtx)
	return l.BannerList(in)
}

func (s *GoodsServer) CreateBanner(ctx context.Context, in *goods.BannerRequest) (*goods.BannerResponse, error) {
	l := logic.NewCreateBannerLogic(ctx, s.svcCtx)
	return l.CreateBanner(in)
}

func (s *GoodsServer) DeleteBanner(ctx context.Context, in *goods.BannerRequest) (*goods.Empty, error) {
	l := logic.NewDeleteBannerLogic(ctx, s.svcCtx)
	return l.DeleteBanner(in)
}

func (s *GoodsServer) UpdateBanner(ctx context.Context, in *goods.BannerRequest) (*goods.Empty, error) {
	l := logic.NewUpdateBannerLogic(ctx, s.svcCtx)
	return l.UpdateBanner(in)
}

// 品牌分类
func (s *GoodsServer) CategoryBrandList(ctx context.Context, in *goods.CategoryBrandFilterRequest) (*goods.CategoryBrandListResponse, error) {
	l := logic.NewCategoryBrandListLogic(ctx, s.svcCtx)
	return l.CategoryBrandList(in)
}

// 通过category获取brands
func (s *GoodsServer) GetCategoryBrandList(ctx context.Context, in *goods.CategoryInfoRequest) (*goods.BrandListResponse, error) {
	l := logic.NewGetCategoryBrandListLogic(ctx, s.svcCtx)
	return l.GetCategoryBrandList(in)
}

func (s *GoodsServer) CreateCategoryBrand(ctx context.Context, in *goods.CategoryBrandRequest) (*goods.CategoryBrandResponse, error) {
	l := logic.NewCreateCategoryBrandLogic(ctx, s.svcCtx)
	return l.CreateCategoryBrand(in)
}

func (s *GoodsServer) DeleteCategoryBrand(ctx context.Context, in *goods.CategoryBrandRequest) (*goods.Empty, error) {
	l := logic.NewDeleteCategoryBrandLogic(ctx, s.svcCtx)
	return l.DeleteCategoryBrand(in)
}

func (s *GoodsServer) UpdateCategoryBrand(ctx context.Context, in *goods.CategoryBrandRequest) (*goods.Empty, error) {
	l := logic.NewUpdateCategoryBrandLogic(ctx, s.svcCtx)
	return l.UpdateCategoryBrand(in)
}
