// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: inventory.proto

package server

import (
	"context"

	"shop/inventory/internal/logic"
	"shop/inventory/internal/svc"
	"shop/inventory/inventory"
)

type InventoryServer struct {
	svcCtx *svc.ServiceContext
	inventory.UnimplementedInventoryServer
}

func NewInventoryServer(svcCtx *svc.ServiceContext) *InventoryServer {
	return &InventoryServer{
		svcCtx: svcCtx,
	}
}

func (s *InventoryServer) SetInv(ctx context.Context, in *inventory.GoodsInventoryInfo) (*inventory.Empty, error) {
	l := logic.NewSetInvLogic(ctx, s.svcCtx)
	return l.SetInv(in)
}

func (s *InventoryServer) InvDetail(ctx context.Context, in *inventory.GoodsInventoryInfo) (*inventory.GoodsInventoryInfo, error) {
	l := logic.NewInvDetailLogic(ctx, s.svcCtx)
	return l.InvDetail(in)
}

func (s *InventoryServer) Sell(ctx context.Context, in *inventory.SellInfo) (*inventory.Empty, error) {
	l := logic.NewSellLogic(ctx, s.svcCtx)
	return l.Sell(in)
}

func (s *InventoryServer) Reback(ctx context.Context, in *inventory.SellInfo) (*inventory.Empty, error) {
	l := logic.NewRebackLogic(ctx, s.svcCtx)
	return l.Reback(in)
}
