// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: userop.proto

package server

import (
	"context"

	"shop/userop/internal/logic"
	"shop/userop/internal/svc"
	"shop/userop/userop"
)

type UseropServer struct {
	svcCtx *svc.ServiceContext
	userop.UnimplementedUseropServer
}

func NewUseropServer(svcCtx *svc.ServiceContext) *UseropServer {
	return &UseropServer{
		svcCtx: svcCtx,
	}
}

func (s *UseropServer) GetMessageList(ctx context.Context, in *userop.MessageRequest) (*userop.MessageListResponse, error) {
	l := logic.NewGetMessageListLogic(ctx, s.svcCtx)
	return l.GetMessageList(in)
}

func (s *UseropServer) CreateMessage(ctx context.Context, in *userop.MessageRequest) (*userop.MessageResponse, error) {
	l := logic.NewCreateMessageLogic(ctx, s.svcCtx)
	return l.CreateMessage(in)
}

func (s *UseropServer) GetFavList(ctx context.Context, in *userop.UserFavRequest) (*userop.UserFavListResponse, error) {
	l := logic.NewGetFavListLogic(ctx, s.svcCtx)
	return l.GetFavList(in)
}

func (s *UseropServer) AddUserFav(ctx context.Context, in *userop.UserFavRequest) (*userop.Empty, error) {
	l := logic.NewAddUserFavLogic(ctx, s.svcCtx)
	return l.AddUserFav(in)
}

func (s *UseropServer) DeleteUserFav(ctx context.Context, in *userop.UserFavRequest) (*userop.Empty, error) {
	l := logic.NewDeleteUserFavLogic(ctx, s.svcCtx)
	return l.DeleteUserFav(in)
}

func (s *UseropServer) GetUserFavDetail(ctx context.Context, in *userop.UserFavRequest) (*userop.Empty, error) {
	l := logic.NewGetUserFavDetailLogic(ctx, s.svcCtx)
	return l.GetUserFavDetail(in)
}

func (s *UseropServer) GetAddressList(ctx context.Context, in *userop.GetAddressRequest) (*userop.AddressListResponse, error) {
	l := logic.NewGetAddressListLogic(ctx, s.svcCtx)
	return l.GetAddressList(in)
}

func (s *UseropServer) CreateAddress(ctx context.Context, in *userop.GetAddressRequest) (*userop.AddressResponse, error) {
	l := logic.NewCreateAddressLogic(ctx, s.svcCtx)
	return l.CreateAddress(in)
}

func (s *UseropServer) UpdateAddress(ctx context.Context, in *userop.GetAddressRequest) (*userop.Empty, error) {
	l := logic.NewUpdateAddressLogic(ctx, s.svcCtx)
	return l.UpdateAddress(in)
}

func (s *UseropServer) DeleteAddress(ctx context.Context, in *userop.GetAddressRequest) (*userop.Empty, error) {
	l := logic.NewDeleteAddressLogic(ctx, s.svcCtx)
	return l.DeleteAddress(in)
}
