// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: userop.proto

package useropclient

import (
	"context"

	"shop/userop/userop"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddressListResponse = userop.AddressListResponse
	AddressResponse     = userop.AddressResponse
	Empty               = userop.Empty
	GetAddressRequest   = userop.GetAddressRequest
	MessageListResponse = userop.MessageListResponse
	MessageRequest      = userop.MessageRequest
	MessageResponse     = userop.MessageResponse
	UserFavListResponse = userop.UserFavListResponse
	UserFavRequest      = userop.UserFavRequest
	UserFavResponse     = userop.UserFavResponse

	Userop interface {
		GetMessageList(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageListResponse, error)
		CreateMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
		GetFavList(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*UserFavListResponse, error)
		AddUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error)
		DeleteUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error)
		GetUserFavDetail(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error)
		GetAddressList(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*AddressListResponse, error)
		CreateAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*AddressResponse, error)
		UpdateAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*Empty, error)
		DeleteAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultUserop struct {
		cli zrpc.Client
	}
)

func NewUserop(cli zrpc.Client) Userop {
	return &defaultUserop{
		cli: cli,
	}
}

func (m *defaultUserop) GetMessageList(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageListResponse, error) {
	client := userop.NewUseropClient(m.cli.Conn())
	return client.GetMessageList(ctx, in, opts...)
}

func (m *defaultUserop) CreateMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	client := userop.NewUseropClient(m.cli.Conn())
	return client.CreateMessage(ctx, in, opts...)
}

func (m *defaultUserop) GetFavList(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*UserFavListResponse, error) {
	client := userop.NewUseropClient(m.cli.Conn())
	return client.GetFavList(ctx, in, opts...)
}

func (m *defaultUserop) AddUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := userop.NewUseropClient(m.cli.Conn())
	return client.AddUserFav(ctx, in, opts...)
}

func (m *defaultUserop) DeleteUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := userop.NewUseropClient(m.cli.Conn())
	return client.DeleteUserFav(ctx, in, opts...)
}

func (m *defaultUserop) GetUserFavDetail(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := userop.NewUseropClient(m.cli.Conn())
	return client.GetUserFavDetail(ctx, in, opts...)
}

func (m *defaultUserop) GetAddressList(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*AddressListResponse, error) {
	client := userop.NewUseropClient(m.cli.Conn())
	return client.GetAddressList(ctx, in, opts...)
}

func (m *defaultUserop) CreateAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*AddressResponse, error) {
	client := userop.NewUseropClient(m.cli.Conn())
	return client.CreateAddress(ctx, in, opts...)
}

func (m *defaultUserop) UpdateAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := userop.NewUseropClient(m.cli.Conn())
	return client.UpdateAddress(ctx, in, opts...)
}

func (m *defaultUserop) DeleteAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := userop.NewUseropClient(m.cli.Conn())
	return client.DeleteAddress(ctx, in, opts...)
}
